import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
    './storage/framework/views/*.php',
    './resources/views/**/*.blade.php',
  ],

  theme: {
    extend: {
      colors: {
        'surface-container-highest': '#e1e3e4',
        'on-primary-fixed': '#410003',
        'on-primary-container': '#ffc8c2',
        'inverse-surface': '#2e3132',
        'primary': '#8f000d',
        'secondary': '#5f5e5e',
        'primary-container': '#b22222',
        'primary-fixed': '#ffdad6',
        'on-error': '#ffffff',
        'surface-tint': '#b52424',
        'error': '#ba1a1a',
        'background': '#f8f9fa',
        'on-error-container': '#93000a',
        'tertiary': '#735c00',
        'on-tertiary-container': '#4e3d00',
        'tertiary-container': '#cca72f',
        'error-container': '#ffdad6',
        'surface-container-high': '#e7e8e9',
        'on-secondary-fixed-variant': '#474746',
        'surface-dim': '#d9dadb',
        'on-tertiary-fixed-variant': '#574500',
        'inverse-on-surface': '#f0f1f2',
        'outline': '#8e706d',
        'outline-variant': '#e2beba',
        'on-tertiary-fixed': '#241a00',
        'on-secondary-container': '#636262',
        'on-primary-fixed-variant': '#92030f',
        'secondary-container': '#e2dfde',
        'surface': '#f8f9fa',
        'inverse-primary': '#ffb4ac',
        'surface-container-lowest': '#ffffff',
        'on-primary': '#ffffff',
        'on-surface': '#191c1d',
        'on-tertiary': '#ffffff',
        'surface-variant': '#e1e3e4',
        'on-secondary-fixed': '#1b1c1c',
        'tertiary-fixed': '#ffe088',
        'surface-container-low': '#f3f4f5',
        'on-surface-variant': '#5a403e',
        'surface-container': '#edeeef',
        'tertiary-fixed-dim': '#e9c349',
        'secondary-fixed': '#e5e2e1',
        'on-background': '#191c1d',
        'secondary-fixed-dim': '#c8c6c5',
        'surface-bright': '#f8f9fa',
        'primary-fixed-dim': '#ffb4ac',
        'on-secondary': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        gutter: '24px',
        'container-max': '1280px',
        'margin-mobile': '16px',
        'section-gap': '80px',
        'margin-desktop': '40px',
        base: '8px',
      },
      fontFamily: {
        'label-caps': ['Inter', ...defaultTheme.fontFamily.sans],
        'body-md': ['Inter', ...defaultTheme.fontFamily.sans],
        'display-lg-mobile': ['Montserrat', ...defaultTheme.fontFamily.sans],
        'display-lg': ['Montserrat', ...defaultTheme.fontFamily.sans],
        'headline-md': ['Montserrat', ...defaultTheme.fontFamily.sans],
        'headline-sm': ['Montserrat', ...defaultTheme.fontFamily.sans],
        'body-lg': ['Inter', ...defaultTheme.fontFamily.sans],
        'price-display': ['Montserrat', ...defaultTheme.fontFamily.sans],
      },
      fontSize: {
        'label-caps': ['12px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'display-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'price-display': ['22px', { lineHeight: '1.0', fontWeight: '700' }],
      },
    },
  },

  plugins: [forms],
};
